### GET hello
GET http://localhost:8888/hello


### GET ga
GET http://localhost:8888/ga?name=ga

### POST user
POST http://localhost:8888/gw/cn.syx.rpc.demo.api.UserService
Content-Type: application/json

{
  "service": "cn.syx.rpc.demo.api.UserService",
  "methodSign": "findById(int)",
  "args": [10000]
}